version: 0.2

phases:

  pre_build:
    commands:
      - echo Logging in to DockerHub
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  build:
    commands:
      - echo Building Docker image
      - docker build -t brain-tasks-app .

      - echo Tagging Docker image
      - docker tag brain-tasks-app sushil2112/brain-tasks-app:v1

  post_build:
    commands:
      - echo Pushing Docker image
      - docker push sushil2112/brain-tasks-app:v1
