version: 0.2

phases:

  pre_build:
    commands:
      - echo Logging in to DockerHub
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

  build:
    commands:
      - echo Building Docker image
      - docker build -t brain-tasks-app .

      - echo Tagging Docker image
      - docker tag brain-tasks-app sushil2112/brain-tasks-app:v1

  post_build:
    commands:
      - echo Pushing Docker image
      - docker push sushil2112/brain-tasks-app:v1
